# Generated by Django 4.2.23 on 2025-08-10 17:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Construction Company', max_length=200)),
                ('tagline', models.CharField(default='Building Your Dreams', max_length=300)),
                ('about_us', ckeditor_uploader.fields.RichTextUploadingField()),
                ('mission_statement', models.TextField()),
                ('years_experience', models.PositiveIntegerField(default=10)),
                ('projects_completed', models.PositiveIntegerField(default=100)),
                ('happy_clients', models.PositiveIntegerField(default=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='company/')),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Project Gallery',
                'ordering': ['order', '-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_position', models.CharField(blank=True, max_length=100)),
                ('client_company', models.CharField(blank=True, max_length=100)),
                ('testimonial', models.TextField()),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
